x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  mtg:
    container_name: mtg
    image: nineseconds/mtg:2
    command: simple-run -n 8.8.8.8 -t 30s -a 1mib 0.0.0.0:3128 ${MTG_SECRET}
    ports:
      - 443:3128
    logging: *logging

