log:
  level: INFO

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

entryPoints:
#  http-entry:
#    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: https-entry
#          scheme: https
  https-entry:
    address: ":443"

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: rustam.nazarov@gmail.com
#      storage: /etc/traefik/acme.json
#      httpChallenge:
#        entrypoint: http-entry

